### ISSUE TITLE
Feature: Table sorting

### ISSUE THREAD

**Issue by garaiza-93** [TF2Autobot/tf2autobot-gui#12]
The table is created with Vue, but does not sort. Being able to click the column titles to sort the table would be great.

I found this resource: https://www.raymondcamden.com/2018/02/08/building-table-sorting-and-pagination-in-vuejs//

There's also this demo: https://codepen.io/pespantelis/pen/ojwgPB

**Comment by arik123** [comment]
Superseded by #15
