### ISSUE TITLE
[Bug] EACCES permission denied 0.0.0.0:80 regardless of configured port + Thoughts on the Project

### ISSUE THREAD

**Issue by zudsniper** [TF2Autobot/tf2autobot-gui#14]
## Problem  
I'm trying to attach this repo to a single `tf2autobot` `v5.8.1` from `master` branch 
> _my conclusion from the conversations in discord `help-gui` channel was that the gui repository was merged IPC branch -> master, so it should be level with the latest._  

Notably, **the gui actually still starts**, and the `npm run build-back` **doesn't fail**, I just noticed this strange "permissions error", and noticed that, even with my configuration set to custom ports, the `0.0.0.0:80` address was still used. Here is a log dump

### Logs
this is the output of `pm2 log`.    
```diff
home/zod/.pm2/logs/GUI-out.log last 15 lines:
- 0|GUI      | Error message: listen EACCES: permission denied 0.0.0.0:80
- 0|GUI      | Error stack: Error: listen EACCES: permission denied 0.0.0.0:80
  0|GUI      |     at Server.setupListenHandle [as _listen2] (node:net:1446:21)
  0|GUI      |     at listenInCluster (node:net:1511:12)
  0|GUI      |     at Server.listen (node:net:1599:7)
  0|GUI      |     at /home/zod/autobots/tf2autobot-gui/dist/server/index.js:63:24
  0|GUI      |     at /home/zod/autobots/tf2autobot-gui/node_modules/@tf2autobot/tf2-schema/index.js:63:20
  0|GUI      |     at /home/zod/autobots/tf2autobot-gui/node_modules/@tf2autobot/tf2-schema/index.js:180:17
  0|GUI      |     at /home/zod/autobots/tf2autobot-gui/node_modules/async/dist/async.js:3681:19
  0|GUI      |     at wrapper (/home/zod/autobots/tf2autobot-gui/node_modules/async/dist/async.js:271:20)
  0|GUI      |     at iterateeCallback (/home/zod/autobots/tf2autobot-gui/node_modules/async/dist/async.js:427:28)
- 0|GUI      |     at /home/zod/autobots/tf2autobot-gui/node_modules/async/dist/async.js:327:20
- 0|GUI      | Please report this bug @ https://github.com/TF2Autobot/tf2autobot-gui/issues/new
+ 0|GUI      | tf2autobot-gui v3.0.1 is starting...
+ 0|GUI      | server listening on port 3080
```  
<sub> _using `diff` syntax highlighting for this is beautiful im patting myself on the back_ </sub>  

---  

## Solutions
This is probably a quickfix -- I just don't have time to find it at the moment. If I get a free moment, I will find it and make a PR, but I wanted to report this issue _(exclusively because I was told to in the console)_  

I have also _never_ seen this error, not just on this project, but ever at all on the internet as far as I can recall... which is kinda cool I guess  

![error for website on port 3080](https://github.com/TF2Autobot/tf2autobot-gui/assets/16076573/1a73178a-8f49-4586-a45b-3c18d72e489f)  

> _that issue seemed to resolve itself, and eventually I am pushed through steam `OpenIDv2`, and then I am eventually greeted with this fellow_  

<div align="center">

![no bots connected](https://github.com/TF2Autobot/tf2autobot-gui/assets/16076573/712a5136-e22f-4d56-9b84-e69940e1fa16)

#### just wanted to start this discussion.  

</div>  

---  

## Future / Note

Overall thank you [@arik123](https://github.com/arik123) and [@ZeusJunior](https://github.com/ZeusJunior) for all of your work on this project, and **for releasing it publicly for free**. The same obviously to the OGs, [@idinium96](https://github.com/idinium96) and [@Nicklason](https://github.com/nicklason). Thank you for opening your work to the public.  

I hope to see, and contribute to, development as it progresses, and I'm excited about the future of the tool -- thinking like customPricer integration API for GUI to allow for pricer to emit and ingest queries, that coupled with an example and a wiki page on how to build a "customPricer Controller" page, adding perhaps Prometheus + Grafana for analytics gathering & display respectively, a robust authentication system that _crucially_ is NOT mainly reliant on Steam[^1] -- perhaps MFA where user must sign-in with both Discord and with Steam, and still include the option for 2FA via Authenticator app, proxying/rate-limiting management / data[^2], customizable live monitoring & charts & graphs & such (think `btop++` meets some brokerage firms' online investment dashboard)... _anyway_ I am rambling but this is to say, I look forward to seeing where this project ends up. 

> _from [zod](https://gh.zod.tf)_  

[^1]: By no means am I intending to blame gladiator at all here -- the dependency that ***EVERYONE*** used had a vulnerability that went undiscovered for 11 years. I don't see a world where that can be called "incompetence" or a "lack of cybersecurity prowess" on the part of the gladiator team. <sub>Love you guys</sub>  
[^2]: [(this project for rate-limiting is really cool)](https://github.com/SGrondin/bottleneck)

**Comment by arik123** [comment]
So, for your first assumption - support for the GUI is NOT yet on the master branch, it will come with v6, for now you have to switch to `IPC` branch.  
And if you refer to the [source](https://github.com/TF2Autobot/tf2autobot-gui/blob/rework-V3/src/server/index.ts#L41-L51) 
you might find that you set the wrong port for your usecase.
As for your "notes", I disagree with not using Steam auth, just because a few packages from random people on the internet were vulnerable, if I find some time I will change the vulnerable passport-steam to my own OpenID implementation. But I do agree with you that if people really want to run this live on the internet, then 2FA would be a good addition.

**Comment by zudsniper** [comment]
> So, for your first assumption - support for the GUI is NOT yet on the master branch, it will come with v6, for now you have to switch to `IPC` branch. And if you refer to the [source](https://github.com/TF2Autobot/tf2autobot-gui/blob/rework-V3/src/server/index.ts#L41-L51) you might find that you set the wrong port for your usecase. As for your "notes", I disagree with not using Steam auth, just because a few packages from random people on the internet were vulnerable, if I find some time I will change the vulnerable passport-steam to my own OpenID implementation. But I do agree with you that if people really want to run this live on the internet, then 2FA would be a good addition.

@arik123 I swapped to the `IPC` branch after I saw idi talk about it and $voilà$. mea culpa, that was my bad.  
as for Steam & its OpenIDv2 implementation with `passport-steam`, I really didn't mean to insinuate you remove it at all; on the contrary, I meant only to posit that other options be added ***in addition*** to authentication through Steam. I agree with your assessment that it is a reasonable conclusion made that Steam authentication is easy to use, robust, and inherently related to `TF2Autobot`, so it saves lots of time and decreases possible vulnerabilities when compared to using something like your own authentication servers.  

I apologize if my comments were incendiary or irritating at all; this was not my intention. I am simply enthusiastic about your project. Hopefully that is elucidated with this.

**Comment by zudsniper** [comment]
This issue seems to be resolved when using the `IPC` branch of [`tf2autobot`](https://github.com/TF2Autobot/tf2autobot) so I am closing this issue
